# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import score_pb2 as score__pb2


class ScoreStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetScore = channel.unary_unary(
        '/Score/GetScore',
        request_serializer=score__pb2.Empty.SerializeToString,
        response_deserializer=score__pb2.Game.FromString,
        )


class ScoreServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetScore(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ScoreServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetScore': grpc.unary_unary_rpc_method_handler(
          servicer.GetScore,
          request_deserializer=score__pb2.Empty.FromString,
          response_serializer=score__pb2.Game.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Score', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
