# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: videogame.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='videogame.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0fvideogame.proto\"\x07\n\x05\x45mpty\"#\n\x04Game\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\"#\n\x0cGameResponse\x12\x13\n\x04game\x18\x01 \x01(\x0b\x32\x05.Game\"+\n\x14GameMultipleResponse\x12\x13\n\x04game\x18\x01 \x03(\x0b\x32\x05.Game2e\n\tVideogame\x12\'\n\rSaveVideogame\x12\x05.Game\x1a\r.GameResponse\"\x00\x12/\n\x0cGetVideogame\x12\x06.Empty\x1a\x15.GameMultipleResponse\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=26,
)


_GAME = _descriptor.Descriptor(
  name='Game',
  full_name='Game',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='Game.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='Game.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=63,
)


_GAMERESPONSE = _descriptor.Descriptor(
  name='GameResponse',
  full_name='GameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='GameResponse.game', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=100,
)


_GAMEMULTIPLERESPONSE = _descriptor.Descriptor(
  name='GameMultipleResponse',
  full_name='GameMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='game', full_name='GameMultipleResponse.game', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=102,
  serialized_end=145,
)

_GAMERESPONSE.fields_by_name['game'].message_type = _GAME
_GAMEMULTIPLERESPONSE.fields_by_name['game'].message_type = _GAME
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Game'] = _GAME
DESCRIPTOR.message_types_by_name['GameResponse'] = _GAMERESPONSE
DESCRIPTOR.message_types_by_name['GameMultipleResponse'] = _GAMEMULTIPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'videogame_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  })
_sym_db.RegisterMessage(Empty)

Game = _reflection.GeneratedProtocolMessageType('Game', (_message.Message,), {
  'DESCRIPTOR' : _GAME,
  '__module__' : 'videogame_pb2'
  # @@protoc_insertion_point(class_scope:Game)
  })
_sym_db.RegisterMessage(Game)

GameResponse = _reflection.GeneratedProtocolMessageType('GameResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMERESPONSE,
  '__module__' : 'videogame_pb2'
  # @@protoc_insertion_point(class_scope:GameResponse)
  })
_sym_db.RegisterMessage(GameResponse)

GameMultipleResponse = _reflection.GeneratedProtocolMessageType('GameMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMEMULTIPLERESPONSE,
  '__module__' : 'videogame_pb2'
  # @@protoc_insertion_point(class_scope:GameMultipleResponse)
  })
_sym_db.RegisterMessage(GameMultipleResponse)



_VIDEOGAME = _descriptor.ServiceDescriptor(
  name='Videogame',
  full_name='Videogame',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=147,
  serialized_end=248,
  methods=[
  _descriptor.MethodDescriptor(
    name='SaveVideogame',
    full_name='Videogame.SaveVideogame',
    index=0,
    containing_service=None,
    input_type=_GAME,
    output_type=_GAMERESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetVideogame',
    full_name='Videogame.GetVideogame',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_GAMEMULTIPLERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_VIDEOGAME)

DESCRIPTOR.services_by_name['Videogame'] = _VIDEOGAME

# @@protoc_insertion_point(module_scope)
